# Generated by Django 2.0 on 2018-03-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tuxing',
            field=models.ImageField(max_length=256, null=True, upload_to='', verbose_name='12'),
        ),
    ]
