# Generated by Django 2.0 on 2018-03-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_test_tuxing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=256, verbose_name='email')),
                ('tel', models.CharField(max_length=256, verbose_name='TEL')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
