# Generated by Django 2.0 on 2018-04-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_information_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_dq_choices', models.SmallIntegerField(choices=[(0, '美西-硅谷-可用区B')], default=0, verbose_name='选择地区')),
                ('serverId', models.CharField(max_length=30, verbose_name='服务器名称')),
                ('master_inner_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='主库IP')),
                ('slave_inner_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='从库IP')),
                ('port', models.SmallIntegerField(blank=True, null=True, verbose_name='端口')),
            ],
        ),
    ]
