# Generated by Django 2.0 on 2018-04-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_sfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfs',
            name='port',
            field=models.CharField(max_length=30, null=True, verbose_name='port'),
        ),
    ]
