# Generated by Django 2.1.1 on 2018-09-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20180926_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='device_type_id',
            field=models.IntegerField(choices=[(1, '服务器'), (2, '交换机'), (3, '防火墙')], default=1, verbose_name='资产类型'),
        ),
    ]
