# Generated by Django 2.1.1 on 2018-09-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_remove_server_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='os_platfrom',
        ),
        migrations.AlterField(
            model_name='server',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
