# Generated by Django 2.1.1 on 2018-09-26 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='user_info',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='users',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='lastest_date',
            new_name='latest_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='cabinet_num',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='cabinet_order',
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to=settings.AUTH_USER_MODEL, verbose_name='业务线联系人'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m', to=settings.AUTH_USER_MODEL, verbose_name='系统管理员'),
        ),
        migrations.DeleteModel(
            name='AdminInfo',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
