# Generated by Django 2.1.1 on 2018-09-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20180926_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='device_type_id',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default=1, max_length=123, verbose_name='类型'),
        ),
    ]
