# Generated by Django 2.1.1 on 2018-09-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20180926_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='device_type_id',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='资产类型'),
        ),
    ]
