# Generated by Django 2.1.1 on 2018-09-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20180926_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='server',
            name='model',
        ),
        migrations.AddField(
            model_name='server',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.BusinessUnit', verbose_name='业务线'),
        ),
    ]
