# Generated by Django 2.1.1 on 2018-11-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20180926_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='权限名称')),
                ('url', models.CharField(max_length=255, verbose_name='URL名称')),
                ('per_method', models.SmallIntegerField(choices=[(1, 'GET'), (2, 'POST')], default=1, verbose_name='请求方法')),
                ('argument_list', models.CharField(blank=True, help_text='多个参数之间用英文半角逗号隔开', max_length=255, null=True, verbose_name='参数列表')),
                ('describe', models.CharField(max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
                'permissions': (('views_student_list', '查看学员信息表'), ('views_student_info', '查看学员详细信息')),
            },
        ),
        migrations.RemoveField(
            model_name='nic',
            name='server_obj',
        ),
        migrations.AlterField(
            model_name='server',
            name='capacity_memory',
            field=models.FloatField(blank=True, null=True, verbose_name='内存容量'),
        ),
        migrations.DeleteModel(
            name='NIC',
        ),
    ]
