# Generated by Django 2.1.1 on 2018-11-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_auto_20181107_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='project',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='项目'),
        ),
    ]
